"""tariffs subscr_left

Revision ID: 2a69f0282e9a
Revises: 565641ba46b0
Create Date: 2018-07-20 17:21:25.715468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a69f0282e9a'
down_revision = '565641ba46b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_plan', sa.Column('subscr_num', sa.Integer(), nullable=False))
    op.drop_column('tariff_plan', 'subscr_left')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_plan', sa.Column('subscr_left', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('tariff_plan', 'subscr_num')
    # ### end Alembic commands ###
