"""tariffs added

Revision ID: 4862f15609fb
Revises: 86f1afe9c59b
Create Date: 2018-07-20 16:02:01.107358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4862f15609fb'
down_revision = '86f1afe9c59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscription', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('plan_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'tariff_plan', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'plan_id')
    op.drop_column('subscription', 'note')
    op.drop_table('tariff_plan')
    # ### end Alembic commands ###
