"""tariffs note added

Revision ID: 6021515e7ccf
Revises: 80bbdcb3b389
Create Date: 2018-07-20 16:08:02.111590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6021515e7ccf'
down_revision = '80bbdcb3b389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'note')
    # ### end Alembic commands ###
