"""user fields

Revision ID: 619ba7561bf8
Revises: dae5cbde5337
Create Date: 2018-07-16 14:50:27.490446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619ba7561bf8'
down_revision = 'dae5cbde5337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
