"""tariffs subscr_left

Revision ID: 7e1a5c82c895
Revises: 6021515e7ccf
Create Date: 2018-07-20 17:06:33.212486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1a5c82c895'
down_revision = '6021515e7ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_plan', sa.Column('subscr_left', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff_plan', 'subscr_left')
    # ### end Alembic commands ###
