"""tariffs note added

Revision ID: 80bbdcb3b389
Revises: 4862f15609fb
Create Date: 2018-07-20 16:07:51.886626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80bbdcb3b389'
down_revision = '4862f15609fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'note')
    op.add_column('tariff_plan', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariff_plan', 'note')
    op.add_column('subscription', sa.Column('note', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
