"""user is confirmed

Revision ID: dae5cbde5337
Revises: 7e65aa7dd215
Create Date: 2018-07-16 14:16:26.954905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae5cbde5337'
down_revision = '7e65aa7dd215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_confirmed')
    # ### end Alembic commands ###
